

SPC5515SBVLQ48R

MMA6856KWR2


select *
from bombase
where target_part='DB04M22M'
'WB00000004M22M'

'DB04M22M'


SELECT distinct UNIT_OF_CONSUMPTION,COMPONENT_QTY,TARGET_PART,BOM_PREFERENCE,COMPONENT, 
COMPONENT_DESCRIPTION,COMPONENT_TYPE,BOM_LINE,BOM_ALTERNATE,COMPONENT_PROD_CLASS
FROM BOMBASE WHERE target_part = 'DB04M22M' AND VALID_THIS_LOC <> 'N' ORDER BY BOM_ALTERNATE, BOM_LINE, BOM_PREFERENCE '


select *
from bombase
where target_part='DE12N89D'




